### ISSUE TITLE
비밀키 충돌 이슈

### ISSUE THREAD

**Issue by Khohyeon** [clean17/Village-Back-Project#38]
firebase를 사용하는데 비밀키 ~~.json 형태가 담겨서 gitguardian 에 걸려서 pr요청시 merge를 하는 과정에서 이런식으로 빨간색x가 나오며 문제가 발생 했습니다.
![image](https://user-images.githubusercontent.com/122351733/234766298-ff6ef2dc-b9a0-454e-8bb5-4e0cac9256a9.png)

**Comment by clean17** [comment]
비밀키를 환경변수 또는 aws cli에 입력해야 할 것 같습니다.
자후 수정 예정입니다.
