### ISSUE TITLE
clean build 과정 이슈발생

### ISSUE THREAD

**Issue by Khohyeon** [clean17/Village-Back-Project#70]
테스트 코드를 다 성공 시키고 ./gradlew clean build 실행을 시켰을 때 value의 값이 한글을 인식 못하는 이슈

**Comment by clean17** [comment]
한글 설정 추가로 해결함

gradle.properties 폴더 생성후 
org.gradle.jvmargs=-Dfile.encoding=UTF-8

buld.gradle 에 다음 코드 추가
build{
	compileJava.options.encoding = 'UTF-8'
	compileTestJava.options.encoding = 'UTF-8'
}

답변자 : 박인우
